# Generated by Django 5.1.2 on 2024-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_photo_options_photo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='people',
            field=models.IntegerField(default=4),
        ),
    ]
